### ISSUE TITLE
下载客户端 发现问题

### ISSUE THREAD

**Issue by siuwaitat** [liuxq/TestGame#4]
你好！大大。

Assets/IGSoft_Tools/FXMaker/ToolScript/ToolScript/FXMakerAsset.cs(152,21): error CS0619: `UnityEditor.EditorApplication.SaveAssets()' is obsolete: `Use AssetDatabase.SaveAssets instead (UnityUpgradable) -> AssetDatabase.SaveAssets()'

大大 为什么下载下来工程文件报这错。。
还有那些脚本都没找到。求助 我是UNITY 5.6的

连clientapp 都说加载脚本无效。。

**Comment by liuxq** [comment]
有接口已经被5.6取消了，我晚上改一下~

**Comment by siuwaitat** [comment]
太好啦！大大！

**Comment by liuxq** [comment]
可以了吧
